export * from './add-rival.command';
export * from './add-stadium.command';
export * from './get-rival.command';
export * from './get-stadium.command';
export * from './register-match.command';
export * from './update-date.command';
export * from './update-rival-town.command';
export * from './update-stadium-capacity.command';
export * from './update-stadium-square-meters.command';
